---
- name: Enable CRB 
  ansible.builtin.command: dnf config-manager --set-enabled crb

- name: Add Kubernetes Repo
  ansible.builtin.yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
    enabled: true
    gpgcheck: true
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

- name: Install packages
  ansible.builtin.dnf:
    name: 
      - "{{ item }}"
    state: present
    disable_gpg_check: false
  loop: "{{ packages }}"

- name: Install extra packages from url
  ansible.builtin.unarchive:
    src: "{{ item.url }}"
    dest: "{{ dest_folder }}/"
    creates: "{{ dest_folder }}/{{ item.name }}"
    extra_opts: "{{ item.opts }}"
    remote_src: yes
    owner: root
  loop: "{{ packages_url }}"
  ignore_errors: true
