name: "Terraform"
description: "Runs terraform"
runs:
  using: "composite"
  steps:
  - run: |
      echo "Terraform init"
    shell: bash
  - run: |
      echo "terraform plan --chdir=stacks/${{ github.job }}"
    shell: bash
