---
- name: Set Selinux mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive


- name: SSHD config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
  loop:
    - { key: "ClientAliveCountMax", value: 7 }
    - { key: "ClientAliveInterval", value: 180 }
  notify:
    - Restart sshd
