name: 'Memory'

on:
  workflow_dispatch:
    inputs:
      tenant-id:
        type: choice
        description: strack
        default: all
        options:
        - all
        - arf-prd-we
        - mry-prd-we
        - arf-stg-we
  push:
    branches:
      - main


jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform
        uses: ./.github/actions/tfplan

  mry-prd-we:
    needs: [core]
    if: inputs.tenant-id == 'mry-prd-we' || inputs.tenant-id == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: memo-plan
        name: plan
        run: |
          echo "TF plan memo"

  mry-prd-uae:
    needs: [core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tfplan
        name: "Terraform Plan"

  mry-stg-we:
    needs: [core]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"

  mry-stg-uae:
    needs: [core]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"

  arf-prd-we:
    needs: [mry-prd-we]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"

  arf-stg-we:
    needs: [mry-stg-we, arf-prd-we]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"
  
  edi-prd-we:
    needs: [mry-prd-we]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"
