name: 'Memory'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: tf-plan
        name: plan
        run: |
          echo "terraform plan core"
  
  mry-prd-we:
    needs: [core]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: memo-plan
        name: plan
        run: |
          echo "TF plan memo"

  mry-prd-uae:
    needs: [core]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: memo-plan
        name: plan
        run: |
          echo "TF plan memo"

  mry-stg-we:
    needs: [core]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"

  mry-stg-uae:
    needs: [core]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"

  arf-prd-we:
    needs: [mry-prd-we]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"

  arf-prd-stg:
    needs: [mry-stg-we, arf-prd-we]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"
  
  edi-prd-we:
    needs: [mry-prd-we]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: plan
        run: |
          echo "TF plan memo"
